### ISSUE TITLE
Serialization assertion plan

### ISSUE THREAD

**Issue by linesword** [yuvraj108c/ComfyUI-Depth-Anything-Tensorrt#2]
Error: [TRT] [E] 1: [runtime.cpp::parsePlan::314] Error Code 1: Serialization (Serialization assertion plan->header.magicTag == rt::kPLAN_MAGIC_TAG failed.)
File "/root/ComfyUI/custom_nodes/ComfyUI-Depth-Anything-Tensorrt/__init__.py", line 38, in main

System Info: Ubuntu 20.04 LTS, Cuda 12.1, Tensorrt 8.6.1, Python 3.10, RTX3090 GPU

I used your code and I also tried to re-export the onnx model, but still this error, is it because of the cuda version?

**Comment by yuvraj108c** [comment]
Hello, there a  couple of solutions online for this error. Hopefully, you can try them and fix the issue.
It might be different tensorrt versions when building and using the engine.
