### ISSUE TITLE
Model Reloading

### ISSUE THREAD

**Issue by BuffMcBigHuge** [yuvraj108c/ComfyUI-Depth-Anything-Tensorrt#8]
Every subsequent run reloads the model into memory. For streaming purposes, it adds lots of latency. Ideally the model should be cached in memory.

**Comment by BuffMcBigHuge** [comment]
Added the feature:

https://github.com/yuvraj108c/ComfyUI-Depth-Anything-Tensorrt/pull/9/files

**Comment by yuvraj108c** [comment]
Thanks for the PR. I merged it.
